# Generated by Django 4.2.7 on 2023-12-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_code_expiration',
            field=models.DateTimeField(),
        ),
    ]
