# Generated by Django 4.2.7 on 2023-11-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_slider_alter_answer_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='file',
            new_name='image',
        ),
    ]
