# Generated by Django 4.2.7 on 2023-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_file_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='paid_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'E-sewa'), ('khalti', 'Khalti')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases',
            name='payment_slip',
            field=models.ImageField(default=1, upload_to='paymentslip/'),
            preserve_default=False,
        ),
    ]
