# Generated by Django 4.2.7 on 2023-12-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_purchases_paid_amount_purchases_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answerimage/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questionimage/'),
        ),
    ]
