# Generated by Django 4.2.7 on 2023-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_image_answer_file_remove_questions_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='file',
            new_name='answerfile',
        ),
    ]
