# Generated by Django 4.2.7 on 2023-12-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_file_answer_answerfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_correct',
            new_name='correct',
        ),
    ]
